apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: {{ .Values.replicaCount.client }}
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
      annotations:
        checksum/redeploy: "{{ randAlphaNum 8 }}"
    spec:
      containers:
      - name: client
        image: "{{ .Values.image.repository }}/client:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
          - containerPort: {{ .Values.ports.client }}
            name: client-api
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
