apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recipai-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: reservation-tls
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: client-service
                port:
                  number: 80
