apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: {{ .Values.replicaCount.server }}
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
      annotations:
        checksum/redeploy: "{{ randAlphaNum 8 }}"
    spec:
      containers:
      - name: server
        image: "{{ .Values.image.repository }}/server:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
          - containerPort:  {{ .Values.ports.server }}
            name: server-api
        env:
          - name: GITLAB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: server-secret
                key: gitlab-client-secret
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
