apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: kubernetes-pods
        static_configs:
          - targets:
              - localhost
            labels:
              __path__: /var/log/pods/team-continuous-disappointment_*/*/*.log
        pipeline_stages:
          - cri: {}
          - regex:
              expression: '/var/log/pods/team-continuous-disappointment_(?P<pod>[^_]+)_[^/]+/(?P<container>[^/]+)/'
              source: filename
          - regex:
              expression: '^(?P<service_name>[^-]+)'
              source: pod
          - labels:
              service_name:
              pod: