services:
  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - ./server/.env

  genai:
    build:
      context: ./genai
    container_name: genai
    ports:
      - "8000:8000"
    depends_on:
      - server
    restart: unless-stopped
    env_file:
      - ./genai/.env

  client:
    build:
      context: ./client
      args:
        - NODE_ENV=development
    container_name: client
    ports:
      - "5173:80"
    depends_on:
      - server
    restart: unless-stopped
