services:
  server-service:
    image: ghcr.io/aet-devops25/team-continuous-disappointment/server:latest
    container_name: server
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - ./server/.env

  genai-service:
    image: ghcr.io/aet-devops25/team-continuous-disappointment/genai:latest
    container_name: genai
    ports:
      - "8000:8000"
    depends_on:
      - server-service
      - qdrant-service
    restart: unless-stopped
    env_file:
      - ./genai/.env

  qdrant-service:
    image: qdrant/qdrant
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  client-service:
    image: ghcr.io/aet-devops25/team-continuous-disappointment/client:latest
    container_name: client
    ports:
      - "3000:80"
    depends_on:
      - server-service
    restart: unless-stopped

volumes:
  qdrant_storage:
