services:
  server:
    build: ./server
    image: edkaya/server:latest # todo: change this to the github registry
    container_name: server
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - ./server/.env

  genai:
    build: ./genai
    image: edkaya/genai:latest # todo: change this to the github registry
    container_name: genai
    ports:
      - "8000:8000"
    depends_on:
      - server
    restart: unless-stopped
    env_file:
      - ./genai/.env

  client:
    build: ./client
    image: edkaya/client:latest # todo: change this to the github registry
    container_name: client
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped
    env_file:
      - ./client/.env.development