services:
  server-service:
    build:
      context: ./server
    container_name: server
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - ./server/.env

  genai-service:
    build:
      context: ./genai
    container_name: genai
    ports:
      - "8000:8000"
    depends_on:
      - server-service
      - qdrant-service
    restart: unless-stopped
    env_file:
      - ./genai/.env

  qdrant-service:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  client-service:
    build:
      context: ./client
      args:
        - NODE_ENV=development
    container_name: client
    ports:
      - "5173:80"
    depends_on:
      - server-service
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=recipai
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  qdrant_storage:
  mongodb_data:
