apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  labels:
    app: alertmanager
type: Opaque
stringData:
  alertmanager.yml: |
    global:
      resolve_timeout: 1m

    route:
      receiver: discord-webhook
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 1h

    receivers:
      - name: discord-webhook
        webhook_configs:
          - url: "https://discord.com/api/webhooks/1384597112955867277/YXLiCFAP8G3sXSv0EMNcspAVSeIElReokz2r2LoK-gtB-SxEbiTlplqXsrL09d8pwj4x"
            send_resolved: true