apiVersion: v1
kind: Secret
metadata:
  name: genai-secret
  annotations:
    checksum/redeploy: "{{ randAlphaNum 8 }}"
type: Opaque
stringData:
  api-openai: {{ .Values.secrets.apiOpenAi }}
  api-openwebui: {{ .Values.secrets.apiOpenWebUi }}