spring:
  application:
    name: server
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: ${gitlab.client-id}
          client-secret: ${gitlab.client-secret}
          introspection-uri: ${gitlab.introspection-uri}

gitlab:
  client-secret: ${GITLAB_CLIENT_SECRET:test-secret}
  introspection-uri: https://gitlab.lrz.de/oauth/introspect