spring:
  application:
    name: server
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: ${GITLAB_CLIENT_ID:test-id}
          client-secret: ${GITLAB_CLIENT_SECRET:test-secret}
          introspection-uri: https://gitlab.lrz.de/oauth/introspect
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://admin:admin@127.0.0.1:27017/recipai?authSource=admin}