openapi: 3.0.3
info:
  title: GenAI Module API
  version: 1.0.0

paths:
  /genai/upload:
    post:
      summary: Upload a file for ingestion
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UploadRequest'
      responses:
        '200':
          description: File processed successfully or already uploaded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadResponse'
        '400':
          description: No file provided
        '500':
          description: Server error during ingestion

  /genai/generate:
    post:
      summary: Generate a recipe response using retrieved context and chat history
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateRequest'
      responses:
        '200':
          description: AI-generated recipe response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateResponse'
        '400':
          description: Missing 'query' or 'messages'
        '500':
          description: Server error during generation

components:
  schemas:
    UploadRequest:
      type: object
      properties:
        file:
          type: string
          format: binary
          description: The file to upload and ingest
      required:
        - file

    UploadResponse:
      type: object
      properties:
        message:
          type: string
        error:
          type: string

    GenerateRequest:
      type: object
      required:
        - query
        - messages
      properties:
        query:
          type: string
          description: The user's recipe-related query
        messages:
          type: array
          description: Full conversation history
          items:
            $ref: '#/components/schemas/ChatMessage'

    ChatMessage:
      type: object
      required:
        - role
        - content
      properties:
        role:
          type: string
          enum: [USER, ASSISTANT]
          description: The role in the conversation
        content:
          type: string
          description: The user's message content

    GenerateResponse:
      type: object
      properties:
        response:
          type: string
        error:
          type: string