# Docker image settings
image:
  repository: ghcr.io/aet-devops25/team-continuous-disappointment
  tag: latest

# Hostname for Ingress
host: recipai.student.k8s.aet.cit.tum.de

# Resource limits
resources:
  limits:
    cpu: "1"
    memory: "512Mi"

# Replica count for each service
replicaCount:
  client: 1
  server: 1
  genai: 1

# Port configuration per service
ports:
  client: 80
  server: 8080
  genai: 8000

# Service names
services:
  client: client-service
  server: server-service
  genai: genai-service
  mongodb: mongodb-service
  qdrant: qdrant-service

db:
  adminUsername: admin
  storage: 4Gi

# qdrant vector db
vdb:
  storage: 1Gi

# will be overridden
secrets:
  gitlabClientSecret: "set in CI pipeline"
  mongodbAdminPassword: "set in CI pipeline"
