apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter-prometheus-node-exporter:9100']
      - job_name: 'genai-service'
        static_configs:
          - targets: ['genai-service:8000']
      - job_name: 'api-gw'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['apigw-service:8080']
      - job_name: 'chat'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['chat-service:8082']
      - job_name: 'user'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['user-service:8081']
