apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  strategy:
    type: Recreate
  replicas: {{ .Values.replicaCount.grafana }}
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana-oss:latest
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: {{ .Values.ports.grafana | default 3000 }}
          env:
            - name: GF_SERVER_ROOT_URL
              value: "https://grafana-tcd.student.k8s.aet.cit.tum.de/"
          volumeMounts:
            - name: storage
              mountPath: /var/lib/grafana
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboards-config
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
            - name: alerting-config
              mountPath: /etc/grafana/provisioning/alerting
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: grafana-storage
        - name: datasources
          configMap:
            name: grafana-datasources
        - name: dashboards-config
          configMap:
            name: grafana-dashboard-provider
        - name: dashboards
          projected:
            sources:
              - configMap:
                  name: chat-dashboard
              - configMap:
                  name: genai-dashboard
              - configMap:
                  name: system-dashboard
        - name: alerting-config
          configMap:
            name: grafana-alerting