apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
spec:
  replicas: {{ .Values.replicaCount.server.chat }}
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
      annotations:
        checksum/redeploy: "{{ randAlphaNum 8 }}"
    spec:
      containers:
      - name: chat
        image: "{{ .Values.image.repository }}/chat:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
          - containerPort:  {{ .Values.ports.server.chat }}
            name: chat-api
        env:
          - name: MONGODB_USERNAME
            value: {{ .Values.db.adminUsername }}
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: server-secret
                key: mongodb-password
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
