apiVersion: v1
kind: Secret
metadata:
  name: server-secret
  annotations:
    checksum/redeploy: "{{ randAlphaNum 8 }}"
type: Opaque
stringData:
  gitlab-client-secret: {{ .Values.secrets.gitlabClientSecret }}
  mongodb-password: {{ .Values.secrets.mongodbAdminPassword }}