---
- name: Install Docker Compose and run services
  hosts: all
  vars:
    project_dir: "{{ ansible_env.HOME }}/recipai"
    folders_to_copy:
      - server
      - client
      - genai

  tasks:
    - name: Copy docker-compose.yml
      copy:
        src: "../../docker-compose.yml"
        dest: "{{ project_dir }}/docker-compose.yml"

    - name: Copy secrets
      copy:
        src: ../secrets/.env
        dest: "{{ project_dir }}/.env"

    - name: Stop any running containers
      command: docker compose down
      become: true
      args:
        chdir: "{{ project_dir }}"
      ignore_errors: true

    - name: Run docker compose up
      command: docker compose up -d
      become: true
      args:
        chdir: "{{ project_dir }}"
      environment:
        COMPOSE_DOCKER_CLI_BUILD: "1"
        DOCKER_BUILDKIT: "1"

    - name: Check if containers are running
      command: docker compose ps
      become: true
      args:
        chdir: "{{ project_dir }}"
      register: container_status

    - name: Show containers status
      debug:
        var: container_status.stdout_lines
