---
- name: Install Docker Compose and run services
  hosts: all
  vars:
    project_dir: "{{ ansible_env.HOME }}/recipai"

  tasks:
    - name: Ensure project directory exists
      ansible.builtin.file:
        path: "{{ project_dir }}"
        state: directory

    - name: Ensure client directory exists
      ansible.builtin.file:
        path: "{{ project_dir }}/client"
        state: directory

    - name: Copy docker-compose.yml
      copy:
        src: "../../docker-compose.yml"
        dest: "{{ project_dir }}/docker-compose.yml"

    - name: Copy docker-compose.yml
      copy:
        src: "../files/config.json"
        dest: "{{ project_dir }}/client/config.json"

    - name: Copy secrets
      copy:
        src: ../secrets/secret.env
        dest: "{{ project_dir }}/.env"

    - name: Stop any running containers
      command: docker compose down
      become: true
      args:
        chdir: "{{ project_dir }}"
      ignore_errors: true

    - name: Run docker compose up
      command: docker compose up -d
      become: true
      args:
        chdir: "{{ project_dir }}"
      environment:
        COMPOSE_DOCKER_CLI_BUILD: "1"
        DOCKER_BUILDKIT: "1"

    - name: Check if containers are running
      command: docker compose ps
      become: true
      args:
        chdir: "{{ project_dir }}"
      register: container_status

    - name: Show containers status
      debug:
        var: container_status.stdout_lines
