global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'genai'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['genai-service:8000']

  - job_name: 'server'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['server-service:8080']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']