global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'genai'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['genai-service:8000']

  - job_name: 'api-gw'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['apigw-service:8080']

  - job_name: 'chat'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['chat-service:8082']

  - job_name: 'user'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8081']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']