spring:
  application:
    name: api-gw
  cloud:
    gateway:
      mvc:
        routes:
          - id: genai
            uri: http://genai-service:8000 
            predicates:
              - Path=/genai/**

server:
  port: 8080