spring:
  application:
    name: api-gw
  cloud:
    gateway:
      mvc:
        routes:
          - id: user
            uri: http://localhost:8081
            predicates:
              - Path=/user/**
          - id: chat
            uri: http://localhost:8082
            predicates:
              - Path=/chat/**
server:
  port: 8080
