apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: team-disappointment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: docker.io/edkaya/server:latest # todo: change this to the github registry
        ports:
          - containerPort: 8080
            name: server-api

        resources:
          limits:
            cpu: "1"
            memory: "512Mi"