apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  annotations:
    checksum/redeploy: "{{ randAlphaNum 8 }}"
type: Opaque
stringData:
  admin-password: {{ .Values.secrets.mongodbAdminPassword }}