import React from 'react';

const HowItWorks = () => {
  return (
    <section id="how-it-works" className="how-it-works">
      <h2>How It Works</h2>
      <p>Enter your ingredients, flavor preferences, and dietary needs to get personalized recipes generated by AI.</p>
      <div className="visual-explanation-placeholder">
        <p>[Visual representation of the process: Input {'->'} AI {'->'} Recipe]</p>
      </div>
    </section>
  );
};

export default HowItWorks;