apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    
    alerting:
    alertmanagers:
      - static_configs:
          - targets: ["alertmanager:9093"]

    scrape_configs:
      - job_name: 'genai-service'
        static_configs:
          - targets: ['genai-service:8000']
      - job_name: 'server-service'
        static_configs:
          - targets: ['server-service:8080']