apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
data:
  alert.rules.yml: |
    groups:
      - name: genai-alerts
        rules:
          - alert: HighGenerationDuration
            expr: rate(genai_generation_duration_seconds_sum[5m]) / rate(genai_generation_duration_seconds_count[5m]) > 5
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "GenAI generation duration too high"
              description: "Generation takes longer than 5s on average over 5m window."