apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: team-disappointment
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: client-api