spring:
  application:
    name: user
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: ${GITLAB_CLIENT_ID:60a9e442420a386f2ddff0f60ed0801dd7e826f0710507e982d5afe6aa054334}
          client-secret: ${GITLAB_CLIENT_SECRET:test-secret}
          introspection-uri: https://gitlab.lrz.de/oauth/introspect

server:
  port: 8081