groups:
  - orgId: 1
    name: Generation Alerts
    folder: GenAI
    interval: 1m
    rules:
      - uid: high_gen_duration
        title: High Generation Duration
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              expr: "rate(genai_generation_duration_seconds_sum[5m]) / clamp_min(rate(genai_generation_duration_seconds_count[5m]), 1)"
              format: reduce
              instant: true
              interval: ""
              datasource:
                type: prometheus
                uid: PBFA97CFB590B2093
        reduce:
          reducer: avg
        evaluator:
          type: gt
          params: [15]
        noDataState: OK
        execErrState: Alerting
        for: 1m
        annotations:
          summary: "Generation duration too high"
        labels:
          severity: warning