apiVersion: 1
contactPoints:
    - orgId: 1
      name: discord-webhook
      receivers:
        - uid: aep95aewu00e8d
          type: discord
          settings:
            url: ${DISCORD_WEBHOOK_URL}
            use_discord_username: false
          disableResolveMessage: false
