name: Manual Ansible Playbook Execution

on:
  workflow_dispatch:
    inputs:
      playbook:
        description: "Ansible playbook to run"
        required: true
        type: string

env:
  SERVER_DN: ec2-18-212-178-250.compute-1.amazonaws.com # TODO: Change ip and Username according to aws vm
  DEBUG: true
  SERVER_USERNAME: ubuntu

jobs:
  run-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_VM_KEY }}" > ~/.ssh/sshkey.pem 2>/dev/null
          chmod 600 ~/.ssh/sshkey.pem

      - name: Configure SSH host
        run: |
          echo "Host $SERVER_DN" >> ~/.ssh/config
          echo "  HostName $SERVER_DN" >> ~/.ssh/config
          echo "  User $SERVER_USERNAME" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/sshkey.pem" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Add server to known_hosts
        run: ssh-keyscan -H "$SERVER_DN" >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/sshkey.pem $SERVER_USERNAME@$SERVER_DN 'echo "SSH connection successful"'

      - name: Run Ansible playbook
        run: |
          ansible-playbook --vault-password-file .vault_pass -i ansible/inventory.ini ansible/playbooks/${{ github.event.inputs.playbook }}

      - name: Clean up sensitive files
        if: always()
        run: |
          rm -f .vault_pass
          rm -f ~/.ssh/sshkey.pem
