name: Manual Ansible Playbook Execution

on:
  workflow_dispatch:
    inputs:
      playbook:
        description: "Ansible playbook to run"
        required: true
        type: string
      vault_password:
        description: "Ansible Vault password"
        required: true
        type: string
      ssh_private_key:
        description: "SSH private key for connecting to servers"
        required: true
        type: string

env:
  SERVER_IP: 13.60.81.149 # TODO: Change ip and Username according to aws vm
  SERVER_USERNAME: ubuntu

jobs:
  run-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Create vault password file
        run: |
          VAULT_PASSWORD=$(jq -r '.inputs.vault_password' ${GITHUB_EVENT_PATH})
          echo "::add-mask::${VAULT_PASSWORD}"
          echo $VAULT_PASSWORD > .vault_pass 2>/dev/null

      - name: Setup SSH key
        run: |
          SSH_PRIVATE_KEY=$(jq -r '.inputs.ssh_private_key' ${GITHUB_EVENT_PATH})
          echo "::add-mask::${SSH_PRIVATE_KEY}"
          mkdir -p ~/.ssh
          echo $SSH_PRIVATE_KEY > ~/.ssh/id_rsa 2>/dev/null
          chmod 600 ~/.ssh/id_rsa

      - name: Configure SSH host
        run: |
          echo "Host $SERVER_IP" >> ~/.ssh/config
          echo "  HostName $SERVER_IP" >> ~/.ssh/config
          echo "  User $SERVER_USERNAME" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Add server to known_hosts
        run: ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        run: |
          ansible-playbook --vault-password-file .vault_pass -i ansible/inventory.ini ansible/playbooks/${{ github.event.inputs.playbook }}

      - name: Clean up sensitive files
        if: always()
        run: |
          rm -f .vault_pass
          rm -f ~/.ssh/id_rsa
