name: GenAI CI/CD

on:
  push:
    paths:
      - 'genai/**'
      - '.github/workflows/genai-ci-cd.yml'
    branches:
      - 'main'
      - 'feature/**'

jobs:
  build-and-test:
    if: startsWith(github.ref, 'refs/heads/feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: genai

      - name: Lint Python code
        run: |
          pip install flake8
          flake8 .
        working-directory: genai

      # Test later on

  # docker-release:
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
