name: CI/CD Tests in GenAI

on:
  push:
    paths:
      - 'genai/**'
  pull_request:
    paths:
      - 'genai/**'

jobs:
  test:
    runs-on: ubuntu-latest
    # Setup qdrant for integration tests
    services:
      qdrant:
        image: qdrant/qdrant
        ports:
          - 6333:6333

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run genai tests
        run: |
          pytest