name: CI/CD Tests in GenAI

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'genai/**'
      - '.github/workflows/genai-tests.yml'

  pull_request:
    branches-ignore:
      - main
    paths:
      - 'genai/**'
      - '.github/workflows/genai-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    # Setup qdrant for integration tests
    services:
      qdrant:
        image: qdrant/qdrant
        ports:
          - 6333:6333
    env:
      OPENAI_API_KEY: ${{ secrets.API_OPENAI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: genai

      - name: Run genai tests
        run: |
          cd genai
          pytest