name: Manual Helm deployment

on:
  workflow_dispatch:

jobs:
  helm-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy with Helm
        run: |
          helm -n team-continuous-disappointment upgrade recip-ai ./recipai-chart \
            --set secrets.gitlabClientSecret="${{ secrets.PROD_CLIENT_SECRET }}" \
            --set secrets.gitlabClientSecretDev="${{ secrets.DEV_CLIENT_SECRET }}" \
            --set secrets.mongodbAdminPassword="${{ secrets.MONGODB_ADMIN_PASSWORD }}" \
            --set secrets.apiOpenAi="${{ secrets.API_OPENAI }}" \
            --set secrets.apiOpenWebUi="${{ secrets.API_OPENWEBUI }}"
