name: Server CI/CD

on:
  push:
    branches:
      - 'main'
      - 'feature/**'

jobs:
  # build-and-test:
  #   if: startsWith(github.ref, 'refs/heads/feature/')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up JDK 21
  #       uses: actions/setup-java@v4
  #       with:
  #         distribution: 'temurin'
  #         java-version: 21

  #     - name: Cache Gradle packages
  #       uses: actions/cache@v4
  #       with:
  #         path: |
  #           ~/.gradle/caches
  #           ~/.gradle/wrapper
  #         key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
  #         restore-keys: |
  #           gradle-${{ runner.os }}-

  #     - name: Grant execute permission for gradlew
  #       run: chmod +x gradlew
  #       working-directory: server

  #     - name: Build with Gradle
  #       run: ./gradlew build
  #       working-directory: server

  #     - name: Run tests
  #       run: ./gradlew test
  #       working-directory: server

  docker-release:
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Needed for pushing to GHCR
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up JDK 21
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: 'temurin'
      #     java-version: 21

      # - name: Grant execute permission for gradlew
      #   run: chmod +x gradlew
      #   working-directory: server

      # - name: Build with Gradle
      #   run: ./gradlew build
      #   working-directory: server

      # - name: Run tests
      #   run: ./gradlew test
      #   working-directory: server

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        working-directory: server
        run: docker build -t ghcr.io/AET-DevOps25/team-continuous-disappointment/server:latest .

      - name: Push Docker image
        run: docker push ghcr.io/AET-DevOps25/team-continuous-disappointment/server:latest
