name: Server CI/CD

on:
  push:
    branches:
      - 'main'
      - 'feature/**'

jobs:
  build-and-test:
    if: startsWith(github.ref, 'refs/heads/feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- server part ---
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: server

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: server

      - name: Run tests
        run: ./gradlew test
        working-directory: server

      # --- genai part ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: genai

      - name: Lint genai service
        run: |
          pip install flake8
          flake8 .
        working-directory: genai

  docker-release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: server

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: server

      - name: Run tests
        run: ./gradlew test
        working-directory: server

      # - name: Log in to Docker Hub
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # - name: Build Docker image
      #   run: docker build -t continious-disappointment-server:latest .

      # - name: Push Docker image
      #   run: docker push continious-disappointment-server:latest
